language: java
jdk:
    - openjdk7
    - oraclejdk8
    - oraclejdk9
    - oraclejdk10
    - oraclejdk-ea
branches:
  only:
    - 3.x
services:
  - redis-server
before_install:
  - cp ./toolchains.xml ~/.m2/
  - wget https://github.com/antirez/redis/archive/3.2.3.tar.gz
  - tar -xvzf 3.2.3.tar.gz >/dev/null 2>&1
  - cd redis-3.2.3
  - make >/dev/null 2>&1
  - cd src && nohup ./redis-server --port 6380 --requirepass test &
  - cd ..
before_script:
  - sleep 10
script: "mvn clean package -P travis --batch-mode --quiet"
after_success:
  - mvn clean test jacoco:report coveralls:report --batch-mode --quiet